### ISSUE TITLE
Deploying on Umbraco Cloud pushed payment testmode setting

### ISSUE THREAD

**Issue by FransdeJong** [vendrhub/vendr-deploy#15] opened 2022-03-11 13:28 UTC
**Describe the bug**
If you push changes between environments in Umbraco Cloud the testmode setting in Mollie is also transfered between environments.
This present a huge risk where a shop can run with Mollie in testmode without anyone knowing.

**Steps To Reproduce**
1. Setup Mollie (I think this is the case with all payment providers)
2. Set the local environment to Test Mode
3. Push to live
4. The live environment is now running in test mode to.

**Expected behavior**
I expect the local and dev environment to run in test mode and that they don't transfer test setting to 

**Vendr version:**
Since this is a Cloud related issue I expect it to be an issue on all versions.

**Comment by mattbrailsford** [comment] 2022-03-11 14:18
This is a duplicate of https://github.com/vendrhub/vendr-deploy/issues/14

**Closed as completed by mattbrailsford** 2022-03-11 14:18 UTC
Labels: bug

**Comment by FransdeJong** [comment] 2022-03-11 14:29
I'm sorry, It didn't come up in the search....

**Comment by mattbrailsford** [comment] 2022-03-11 14:39
@FransdeJong no worries. It's like that it's because that issue is on the Vendr Deploy repo rather than the Vendr repo. Not to worry though (I transferred this issue over to that repo)
